// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReqSimulator.API.Data;
using ReqSimulator.API.Models;

#nullable disable

namespace ReqSimulator.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "match_type", new[] { "exact", "semantic", "partial", "missed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "persona_difficulty", new[] { "easy", "medium", "hard" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_type", new[] { "open_ended", "closed", "clarifying", "probing", "leading", "constraint_oriented", "exception_oriented" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "requirement_category", new[] { "functional", "non_functional", "business_rule", "constraint" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sender_type", new[] { "student", "stakeholder" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "student", "lecturer", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReqSimulator.API.Models.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CoverageScore")
                        .HasColumnType("numeric")
                        .HasColumnName("coverage_score");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Feedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback");

                    b.Property<string>("FeedbackVariant")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("feedback_variant");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<int>("MissedCount")
                        .HasColumnType("integer")
                        .HasColumnName("missed_count");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overridden_at");

                    b.Property<Guid?>("OverriddenByLecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("overridden_by_lecturer_id");

                    b.Property<decimal?>("OverriddenCoverageScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overridden_coverage_score");

                    b.Property<int>("PartialCount")
                        .HasColumnType("integer")
                        .HasColumnName("partial_count");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("TotalRequirements")
                        .HasColumnType("integer")
                        .HasColumnName("total_requirements");

                    b.HasKey("Id");

                    b.HasIndex("OverriddenByLecturerId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("evaluation_results", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.ExtractedRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("NormalizationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalization_method");

                    b.Property<string>("NormalizationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("normalization_status");

                    b.Property<string>("NormalizedRequirementData")
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_requirement_data");

                    b.Property<string>("RawRequirementData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_requirement_data");

                    b.Property<string>("RequirementText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement_text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("extracted_requirements", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.FeedbackSurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Actionability")
                        .HasColumnType("integer")
                        .HasColumnName("actionability");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<int>("Helpfulness")
                        .HasColumnType("integer")
                        .HasColumnName("helpfulness");

                    b.Property<int>("NoAnswerLeak")
                        .HasColumnType("integer")
                        .HasColumnName("no_answer_leak");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("uq_feedback_survey_session");

                    b.HasIndex("StudentId");

                    b.ToTable("feedback_survey_responses", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.HiddenRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("actor");

                    b.Property<RequirementCategory>("Category")
                        .HasColumnType("requirement_category")
                        .HasColumnName("category");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GateOrder")
                        .HasColumnType("integer")
                        .HasColumnName("gate_order");

                    b.Property<string>("NormalizedRequirementData")
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_requirement_data");

                    b.Property<string>("Object")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("object");

                    b.Property<string>("Priority")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("RequirementText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement_text");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("requirement_type");

                    b.Property<string>("RevealCondition")
                        .HasColumnType("text")
                        .HasColumnName("reveal_condition");

                    b.Property<PersonaDifficulty>("RevealDifficulty")
                        .HasColumnType("persona_difficulty")
                        .HasColumnName("reveal_difficulty");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("hidden_requirements", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DraftData")
                        .HasColumnType("jsonb")
                        .HasColumnName("draft_data");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("SelectedModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("selected_model");

                    b.Property<Guid?>("SourceArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_artifact_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceUrlsData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_urls_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceArtifactId")
                        .HasDatabaseName("idx_ingestion_jobs_artifact");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("idx_ingestion_jobs_claim");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.LecturerOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("MatchOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("match_overrides");

                    b.Property<decimal?>("NewCoverageScore")
                        .HasColumnType("numeric")
                        .HasColumnName("new_coverage_score");

                    b.Property<decimal?>("OriginalCoverageScore")
                        .HasColumnType("numeric")
                        .HasColumnName("original_coverage_score");

                    b.Property<DateTime>("OverriddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overridden_at");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .HasDatabaseName("idx_lecturer_overrides_evaluation");

                    b.HasIndex("LecturerId");

                    b.ToTable("lecturer_overrides", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<QuestionType?>("DetectedQuestionType")
                        .HasColumnType("question_type")
                        .HasColumnName("detected_question_type");

                    b.Property<string>("DetectedTopic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("detected_topic");

                    b.Property<string>("QuestionQuality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_quality");

                    b.Property<SenderType>("Sender")
                        .HasColumnType("sender_type")
                        .HasColumnName("sender");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("idx_messages_session_time");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommunicationStyle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("communication_style");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<PersonaDifficulty>("Difficulty")
                        .HasColumnType("persona_difficulty")
                        .HasColumnName("difficulty");

                    b.Property<string>("InitialMood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("initial_mood");

                    b.Property<decimal>("InitialPatience")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_patience");

                    b.Property<string>("KnowledgeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("knowledge_level");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("personality_traits");

                    b.Property<string>("RoleTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_title");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<Guid?>("StakeholderId")
                        .HasColumnType("uuid")
                        .HasColumnName("stakeholder_id");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StakeholderId");

                    b.HasIndex("TemplateId");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.PersonaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommunicationStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("communication_style");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<PersonaDifficulty>("Difficulty")
                        .HasColumnType("persona_difficulty")
                        .HasColumnName("difficulty");

                    b.Property<string>("InitialMood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("initial_mood");

                    b.Property<decimal>("InitialPatience")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_patience");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<string>("KnowledgeLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("knowledge_level");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("personality_traits");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TemplateKey")
                        .IsUnique()
                        .HasDatabaseName("uq_persona_templates_key");

                    b.HasIndex("IsActive", "IsSystemDefault")
                        .HasDatabaseName("idx_persona_templates_active_default");

                    b.ToTable("persona_templates", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.RequirementMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid?>("ExtractedRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("extracted_requirement_id");

                    b.Property<Guid>("HiddenRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("hidden_requirement_id");

                    b.Property<ReqSimulator.API.Models.MatchType>("ReqSimulator.API.Models.MatchType")
                        .HasColumnType("match_type")
                        .HasColumnName("match_type");

                    b.Property<ReqSimulator.API.Models.MatchType?>("OverriddenReqSimulator.API.Models.MatchType")
                        .HasColumnType("match_type")
                        .HasColumnName("overridden_match_type");

                    b.Property<decimal?>("SimilarityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("similarity_score");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ExtractedRequirementId");

                    b.HasIndex("HiddenRequirementId");

                    b.ToTable("requirement_matches", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("config_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<PersonaDifficulty>("Difficulty")
                        .HasColumnType("persona_difficulty")
                        .HasColumnName("difficulty");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ScenarioKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scenario_key");

                    b.Property<string>("SerializedConfig")
                        .HasColumnType("text")
                        .HasColumnName("serialized_config");

                    b.Property<string>("SourceUrlsData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_urls_data");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ScenarioKey")
                        .IsUnique()
                        .HasDatabaseName("uq_scenarios_one_active")
                        .HasFilter("is_active");

                    b.HasIndex("ScenarioKey", "IsActive")
                        .HasDatabaseName("idx_scenarios_key_active");

                    b.HasIndex("ScenarioKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_scenarios_key_version");

                    b.ToTable("scenarios", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.ScenarioReviewAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("RequirementCount")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_count");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("SourceUrlsData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_urls_data");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ScenarioId", "ReviewedAt")
                        .HasDatabaseName("idx_scenario_review_audits_scenario_time");

                    b.ToTable("scenario_review_audits", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.SimulationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime?>("FinalizationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalization_expires_at");

                    b.Property<Guid?>("FinalizationLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalization_lease_id");

                    b.Property<DateTime?>("FinalizationStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalization_started_at");

                    b.Property<string>("FinalizationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("finalization_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<string>("PersonaState")
                        .HasColumnType("jsonb")
                        .HasColumnName("persona_state");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StudentId");

                    b.HasIndex("FinalizationStatus", "FinalizationExpiresAt")
                        .HasDatabaseName("idx_sessions_finalization_state");

                    b.ToTable("simulation_sessions", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.SourceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ActualBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("ExpectedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_bytes");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("source_artifacts", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Stakeholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_title");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_stakeholders_scenario_name");

                    b.ToTable("stakeholders", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ReqSimulator.API.Models.EvaluationResult", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.User", "OverriddenByLecturer")
                        .WithMany()
                        .HasForeignKey("OverriddenByLecturerId");

                    b.HasOne("ReqSimulator.API.Models.SimulationSession", "Session")
                        .WithOne("EvaluationResult")
                        .HasForeignKey("ReqSimulator.API.Models.EvaluationResult", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OverriddenByLecturer");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.ExtractedRequirement", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.SimulationSession", "Session")
                        .WithMany("ExtractedRequirements")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.FeedbackSurveyResponse", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.SimulationSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.HiddenRequirement", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.Scenario", "Scenario")
                        .WithMany("HiddenRequirements")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.IngestionJob", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.SourceArtifact", "SourceArtifact")
                        .WithMany()
                        .HasForeignKey("SourceArtifactId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceArtifact");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.LecturerOverride", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.EvaluationResult", "Evaluation")
                        .WithMany("LecturerOverrides")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Message", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.SimulationSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Persona", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.Scenario", "Scenario")
                        .WithMany("Personas")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.Stakeholder", "Stakeholder")
                        .WithMany("Personas")
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReqSimulator.API.Models.PersonaTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scenario");

                    b.Navigation("Stakeholder");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.RequirementMatch", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.EvaluationResult", "Evaluation")
                        .WithMany("Matches")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.ExtractedRequirement", "ExtractedRequirement")
                        .WithMany()
                        .HasForeignKey("ExtractedRequirementId");

                    b.HasOne("ReqSimulator.API.Models.HiddenRequirement", "HiddenRequirement")
                        .WithMany()
                        .HasForeignKey("HiddenRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("ExtractedRequirement");

                    b.Navigation("HiddenRequirement");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Scenario", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.ScenarioReviewAudit", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.Scenario", "Scenario")
                        .WithMany("ReviewAudits")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.SimulationSession", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReqSimulator.API.Models.User", "Student")
                        .WithMany("Sessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Scenario");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.SourceArtifact", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Stakeholder", b =>
                {
                    b.HasOne("ReqSimulator.API.Models.Scenario", "Scenario")
                        .WithMany("Stakeholders")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.EvaluationResult", b =>
                {
                    b.Navigation("LecturerOverrides");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Scenario", b =>
                {
                    b.Navigation("HiddenRequirements");

                    b.Navigation("Personas");

                    b.Navigation("ReviewAudits");

                    b.Navigation("Stakeholders");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.SimulationSession", b =>
                {
                    b.Navigation("EvaluationResult");

                    b.Navigation("ExtractedRequirements");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.Stakeholder", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("ReqSimulator.API.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
